-- copy orders from 'E:/sql data/Table.2--orders.csv' DELIMITER ',' csv header;  
-- SELECT 
--     first_name,
--     city,
--     order_date
-- from 
--     customers  as c
-- join 
--     orders  as o ON c.customer_id = o.customer_id
-- where
--     extract (year from order_date ) = 2023; 
